#! /bin/env ruby

require 'rubygems'
require 'redis'

$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
ip, port = $1, $2
ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
port = port.nil? ? 6379 : port

config = ARGV.any? { |a| a =~ /config/ }

infos = Redis.new(:host => ip, :port => port).info.inject({}) { |h, (k, v)| h[k] = v if k.to_s =~ /^db\d+/ ;h  }.inject({}) { |hash, (dbnum,out)| out =~ /keys=(\d+),expires=(\d+)/ ;hash.update(dbnum => {:keys => $1.to_i, :expires => $2.to_i} )  }

if config
  puts "graph_title Redis Keys"
  puts "graph_category other"

  infos.each { |db, infos| puts "#{db}_keys.label #{db} keys"; puts "#{db}_expires.label #{db} expires" }
else
  infos.each { |db, infos| puts "#{db}_keys.value #{infos[:keys]}"; puts "#{db}_expires.value #{infos[:expires]}" }
end

