#! /bin/env ruby

require 'rubygems'
require 'redis'

$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
ip, port = $1, $2
ip = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
port = port.nil? ? 6379 : port

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_title Redis Connections"
  puts "graph_category other"

  puts "memory.label Connections"
else
  redis = Redis.new(:host => ip, :port => port)
  info  = redis.info

  puts "memory.value" + " " + (info[:connected_clients].to_i - 1).to_s
end

