#! /bin/env ruby

require 'rubygems'
require 'redis'

$0 =~ /_(\d+_\d+_\d+_\d+)_(\d+)$/
ip, port = $1, $2
ip     = ip.nil? ? '127.0.0.1' : ip.gsub!(/_/, '.')
port   = port.nil? ? 6379 : port

config = ARGV.any? { |a| a =~ /config/ }

if config
  puts "graph_title Redis Memory"
  puts "graph_category redis"
  puts "graph_vlabel mem used"
  puts "graph_info This graph monitors the commands rate"
  puts "graph_args --base 1024 -l 0"

  puts "memory.label memory"
  puts "memory.info Amount of mem used by redis"
  puts "memory.type GAUGE"
  puts "memory.min 0"
  puts "memory.draw AREA"

else
  redis = Redis.new(:host => ip, :port => port)
  info  = redis.info

  puts "memory.value" + " " + info['used_memory'].to_s
end
